import { type NextPage } from "next";
import Head from "next/head";
import React, { useRef } from "react";
import { ReactFlowProvider } from "reactflow";
import Canvas from "~/components/Canvas";
import Sidebar from "~/components/Sidebar";

const Home: NextPage = () => {
  const reactFlowWrapper = useRef(null);

  return (
    <>
      <Head>
        <title>yg</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ReactFlowProvider>
          <div className="reactflow-wrapper" ref={reactFlowWrapper}></div>
          <div style={{ height: "100vh" }} className="flex">
            <div className="h-screen w-1/5 bg-gray-100">
              <Sidebar />
            </div>
            <div className="h-screen w-4/5">
              <Canvas reactFlowWrapper={reactFlowWrapper} />
            </div>
          </div>
        </ReactFlowProvider>
      </main>
    </>
  );
};

export default Home;
