import { type NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import Sidebar from "~/components/Sidebar";

import { useCallback, useState } from "react";
import ReactFlow, {
  addEdge,
  Controls,
  Node,
  ReactFlowProvider,
  useEdgesState,
  useNodesState,
} from "reactflow";

const initialNodes: Node[] = [];

let id = 0;
const getId = () => {
  ++id;
  return `flow-id-${id}`;
};

const Home: NextPage = () => {
  const reactFlowWrapper = useRef(null);

  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [reactFlowInstance, setReactFlowInstance] = useState(null);

  const getNodeById = (id: string) => {
    return nodes.find((node) => node.id === id)?.data;
  };

  const submit = () => {
    const body: any = {};
    edges.forEach(({ source: clusterId, target: appId }) => {
      const node = getNodeById(clusterId) as any;
      const numberOfHosts = node.numberOfHosts;
      const cluster = node.label;
      if (!body[cluster]) {
        body[cluster] = { numberOfHosts };
      }
      const app = getNodeById(appId)?.label as string;
      if (!body[cluster][app]) {
        body[cluster][app] = 0;
      }
      body[cluster][app]++;
    });
    console.log(body);
  };

  const onConnect = useCallback(
    (params: any) => setEdges((eds) => addEdge(params, eds)),
    []
  );

  const onDragOver = useCallback((event: any) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = "move";
  }, []);

  const onDrop = useCallback(
    (event: any) => {
      event.preventDefault();

      // @ts-ignore
      const reactFlowBounds = reactFlowWrapper.current.getBoundingClientRect();
      const label = event.dataTransfer.getData("label");
      const type = event.dataTransfer.getData("type");
      const numberOfHosts = Number.parseInt(
        event.dataTransfer.getData("numberOfHosts")
      );

      // @ts-ignore
      const position = reactFlowInstance.project({
        x: event.clientX - reactFlowBounds.left,
        y: event.clientY - reactFlowBounds.top,
      });

      const newNode = {
        id: getId(),
        type,
        position,
        data: { label, numberOfHosts },
      };

      setNodes((nds) => nds.concat(newNode));
    },
    [reactFlowInstance]
  );

  return (
    <>
      <Head>
        <title>yg</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ReactFlowProvider>
          <div className="reactflow-wrapper" ref={reactFlowWrapper}></div>
          <div style={{ height: "100vh" }} className="flex">
            <div className="h-screen w-1/5 bg-gray-100">
              <Sidebar submit={submit} />
            </div>
            <div className="h-screen w-4/5">
              <ReactFlow
                nodes={nodes}
                edges={edges}
                onNodesChange={onNodesChange}
                onEdgesChange={onEdgesChange}
                onConnect={onConnect}
                // @ts-ignore
                onInit={setReactFlowInstance}
                onDrop={onDrop}
                onDragOver={onDragOver}
                fitView
              >
                <Controls />
              </ReactFlow>
            </div>
          </div>
        </ReactFlowProvider>
      </main>
    </>
  );
};

export default Home;
